### ISSUE TITLE
[Bug report]:

### ISSUE THREAD

**Issue by easyfleet** [iotaledger/legacy-migration-tool#144]
### Version

1.0.0

### Description

not enough funds... more than 1000 IOTA.
DOESN'T WORK_

### Expected behaviour

should send the IOTAs

### Actual behaviour

not enough funds... more than 1000 IOTA.
DOESN'T WORK_

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

Tested 5 times on 2 diferents computers

### Operating System

Windows, Mac

### Diagnostics

```shell

```

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

[59aea9d51c42ecac37d0f1016c6090df-migration.log](https://github.com/user-attachments/files/18011950/59aea9d51c42ecac37d0f1016c6090df-migration.log)

### Error Logs

```shell

```

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
The issue `errorMessage: cannot debit (base tokens: XXX) from YYY: not enough funds` has been mitigated, please try the migration again. We apologize for the troubles :pray:
