### ISSUE TITLE
[Bug report]:

### ISSUE THREAD

**Issue by EURODRY** [iotaledger/legacy-migration-tool#146]
### Version

1.0.0

### Description

Today I managed to migrate my IOTA funds to Stardust. The backup password was saved in Notepad format and the file won't load to recover my funds. Please help me understand what I should do next. Thanks in advance! Best regards, Rodica

### Expected behaviour

I don't know what should have opened.

### Actual behaviour

The SeedVault backup password, saved in Notepad, is not loading.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

I need to convert the Notepad document to .kdbx format, but I don't know how. I need help. Please

### Operating System

Windows

### Diagnostics

```shell
Version 1.0.0
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22631
Platform Architecture: x64
CPU Count: 2
Total Memory: 8001.7 MB
Free Memory: 2610.3 MB
```

### Profile Type

Software (Stronghold)

### Crash Status

None of the above

### Error Messages

Version 1.0.0
Language: en
Currency: USD
Node selection: Automatic
Platform: win32
Platform Version: 10.0.22631
Platform Architecture: x64
CPU Count: 2
Total Memory: 8001.7 MB
Free Memory: 2610.3 MB

### Error Logs

```shell

```

### Duplicate declaration

- [x] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Hushg2** [comment]
Hello @begonaalvarezd  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
